datawarehouse:
  outputs:
    dev:
      dataset: "{{ env_var('DBT_DATASET')}}"
      job_execution_timeout_seconds: "{{ env_var('DBT_JOB_TIMEOUT')}}"
      job_retries: "{{ env_var('DBT_JOB_RETRIES') | int }}"
      keyfile: "{{ env_var('DBT_KEYFILE')}}"
      location: "{{ env_var('DBT_LOCATION')}}"
      method: "{{ env_var('DBT_METHOD')}}"
      priority: "{{ env_var('DBT_PRIORITY')}}"
      project: "{{ env_var('DBT_PROJECT')}}"
      threads: "{{ env_var('DBT_THREADS') | int}}"
      type: bigquery
  target: dev
