datawarehouse:
  outputs:
    dev:
      type: bigquery
      method: "{{ env_var('DBT_METHOD')}}"
      project: "{{ env_var('DBT_PROJECT')}}"
      dataset: "{{ env_var('DBT_DATASET')}}"
      keyfile: "{{ env_var('DBT_KEYFILE')}}"
      threads: "{{ env_var('DBT_THREADS') | int}}"
      job_execution_timeout_seconds: "{{ env_var('DBT_JOB_TIMEOUT') | int}}"
      location: "{{ env_var('DBT_LOCATION')}}"
      priority: "{{ env_var('DBT_PRIORITY')}}"
      job_retries: "{{ env_var('DBT_JOB_RETRIES') | int }}"
  target: dev
